name: Release Zapateria

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - name: 猬锔 Checkout c贸digo
        uses: actions/checkout@v3

      - name:  Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name:  Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: И Ejecutar pruebas
        run: pytest test_app.py

      - name:  Mostrar versi贸n
        run: cat version.txt

      - name:  Generar Tag de versi贸n
        if: github.ref == 'refs/heads/main'
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci@example.com"
          version=$(cat version.txt)
          git tag "v$version"
          # Cambia la URL remota para incluir el token
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin "v$version"

      - name:  Simular despliegue
        run: echo "Desplegando versi贸n $(cat version.txt)..."
